### ISSUE TITLE
Missing type definitions for autoEffect, clearEffect

### ISSUE THREAD

**Issue by anukul** [RisingStack/react-easy-state#168]
See issue title

Thanks :)

**Comment by solkimicreb** [comment]
This is a pretty valid concern 😄 I made the necessary changes and will get it checked tomorrow with the TS guys in the team. Expect a new release with the fix tomorrow.

**Comment by peteyycz** [comment]
Hey @anukul! We've just released a new version that includes the type definitions for those functions! 🎉
