### ISSUE TITLE
Mysterious issue in CI -- wondering if anyone else is experiencing this?

### ISSUE THREAD

**Issue by tnrich** [RisingStack/react-easy-state#169]
Hey there! 

I know nobody likes vague issues without a way of reproducing but my colleague @tgreen7 and I have found that using the latest version of @risingstack/react-easy-state 6.2.0 breaks in CI without an error message. However v6.1.3 works fine for us but has that nasty input bug. 

I know a lot has changed between those two versions. Is anyone else experiencing a mysterious break when going from 6.1.3 to 6.2.X ? 

I'll update this with more info as we try to dig deeper into it

Thanks!

**Comment by solkimicreb** [comment]
Can you try v6.2.1? (See [this issue](https://github.com/RisingStack/react-easy-state/issues/164) for context)

**Comment by tnrich** [comment]
@solkimicreb thanks for the idea. It took us a little while but it turns out it was an issue caused by our tests running electron@59. The version of node bundled with electron@59 apparently didn't have support for the spread operator being used in your code base. We're upgrading our testing framework (cypress) to a higher version which should use a node version compatible with spreads. 

Thanks! Hopefully this helps out some other people :)

**Comment by solkimicreb** [comment]
This is a valid issue, thanks for the investigation!

Object spread is a Node 8+ feature while we should support Node 6+. This was on oversight in the babel config which we will fix in the next release.

**Comment by tnrich** [comment]
@solkimicreb this is great news! Let me know when that new feature is released as we're having issues upgrading cypress and would still love to use react-easy-state. Thanks!

**Comment by tnrich** [comment]
@solkimicreb any movement on this one? Thanks!
