### ISSUE TITLE
Best way for destructuring store method context

### ISSUE THREAD

**Issue by jonlepage** [RisingStack/react-easy-state#179]
Hi, is not a `BUG`, but more a question ,is there a good way for destructuring stores methods ?
I noticed that the destructuring made lose context of getter and method of the store.

example of test case without success
```js
export const Store_page = store({
        _data:true,
	method: () => {
		this._data = false;
	},
});

const Module = () => {
	// destructuring store method 
	const { _data, method} = Module;
	// button lose context
	return <Button onClick={() => method()}></Button>;
};
```
```js
export const Store_page = store({
        _data:true,
	method () {
		this._data = false;
	},
});

const Module = () => {
	// destructuring store method 
	const { _data, method} = Module;
	// button lose context
	return <Button onClick={() => method()}></Button>;
};
```
```js
const { _data} = Module;
const method = Module.method ;
const method2 = Module.method2;
....
```
--- 

So i suppose i can only extract method separately ?
this one work 
```js
const { _data} = Module;
const Module = () => {
	// destructuring store method 
	const { _data, method} = Module;
	// button lose context
	return <Button onClick={() => Module.method()}></Button>;
};
....
```
A never really use destructuring in backEnd because of performance, so it new for me in frontEnd.
I just want to be sure i dont do a mistake with react and your store manager.
thanks for any tips :)

**Comment by solkimicreb** [comment]
You can destructure any way if you use the direct reference instead of `this` in your stores.

```jsx
const myStore = store({
  num: 1,
  increment () {
  // use myStore instead of `this` here
    myStore.num++;
  }
})

export default view(() => {
  const { num, increment } = myStore;
  return <button onClick={increment}>{num}</button>
})
```

Does this answer your question?

PS: Please ask questions on StackOverflow in the future (there is a button for that in the new issue page). Issues are for feature requests and bugs only. Thanks 🙂

**Comment by jonlepage** [comment]
oki thanks for you time, yes this hawser my question.
