### ISSUE TITLE
Re-export `observe` and `unobserve`

### ISSUE THREAD

**Issue by buzinas** [RisingStack/react-easy-state#87]
Hey, I've been using `react-easy-state` and I really like it!

My project is a mix of React with some legacy code that I'm currently sharing the same stores.

At some point, I need to listen to the store changes, but since this library only export the `view` and the `store`, there is no way to do it, unless I manually install `@nx-js/observer-util`. 

Would you please re-export `observe` and `unobserve`, so I can wrap them into my own listeners for this use case?

Thanks in advance!

**Comment by solkimicreb** [comment]
Sure, that makes sense. You don't have to install `@nx-js/observer-util` in the meantime. It's a dependency of `react-easy-state`. Installing it again in your package.json is adding the risk of having two different versions of the package (which would be a mess, since it is a stateful package).

**Comment by solkimicreb** [comment]
Thanks for the PR! It will make it into the next release.
