### ISSUE TITLE
components have no name in react devtools" when using "view(()=><comp />)"

### ISSUE THREAD

**Issue by fuxiao126** [RisingStack/react-easy-state#93]
Thanks for an excellent library!

os: macOS 10.14.6
browser: Chrome 76.0.3809.132
react-easy-state@6.1.3
react@16.9.0

components have no name in react devtools" when using "view(()=>\<comp /\>)"

```js
// has name
const RuleItem = ({ config }) => {
  return (
    <xxx config={config} />
  )
}

// no name
const RuleItem = view(({ config }) => {
  return (
    <xxx config={config} />
  )
})
```
![image](https://user-images.githubusercontent.com/7747725/64421210-a10a6280-d0d3-11e9-8914-ae65656c1dbf.png)

**Comment by miraage** [comment]
Could be fixed by adding a `displayName` property to HOCs from `view` function

**Comment by rainmanhhh** [comment]
write like this
`const RuleItem = view(function RuleItem({ config })  {
  return (
    <xxx config={config} />
  )
}`

**Comment by ricardobeat** [comment]
I think the name is being lost due to the use of  `React.memo` here: https://github.com/solkimicreb/react-easy-state/blob/master/src/view.js#L15

**Comment by solkimicreb** [comment]
This is fixed in the new version (@risingstack/react-easy-state v6.2.0). Check the related docs under the "Usage with React Developer Tools" dropdown in [this docs section](https://github.com/RisingStack/react-easy-state#creating-reactive-views).
