### ISSUE TITLE
Is the project still mantained?

### ISSUE THREAD

**Issue by ciaoben** [RisingStack/react-easy-state#95]
We are happy users of react-easy-state, and we love it!

But I am noticing that lately, the repo seems to not be updated anymore. There is a big bug with `react 16.9` that has been neglected until now and other opened issues too.

I would like to know from @solkimicreb if he plans to maintain it or if we should fork it.

Thanks for your work, don't want to be rude or ungrateful, just need to have some news to decide how to handle this scenario.

**Comment by nitelite** [comment]
If you do end up forking and solve some of the problems with input editing etc, I would love a little nudge. Especially if you are unable to get it pulled back into the main repo, so I can switch to your fork instead :) Love the API of this state management lib, but it seems like it might need some love.

**Comment by AlgoTrader** [comment]
Bad luck, the project is no longer maintained

**Comment by nitelite** [comment]
Are there any other projects for global state stores with a lovely API like this one? Looking at mobx and all the other classic alternatives, they all have really annoying usage patterns compared to this one.

**Comment by ctrlplusb** [comment]
@nitelite - [Easy Peasy](https://easy-peasy.now.sh) is directly inspired by this library. That being said, the API is concise, but not as concise as React Easy State. I owe a lot to @solkimicreb ⭐️

I'm sad to see this library fall out of maintenance. I know its a huge burden to maintain a library though. Perhaps people can put themselves forward to become collaborators on this project. @solkimicreb is everything ok with you?

**Comment by AlgoTrader** [comment]
Easy Peasy is redux wrapper. Redux is a single global store that cannot be extended runtime. Redux has overhead - it needs actions, reducers, all that stuff that we either have to write or generate programatically. I no longer need to write ugly Redux stuff, that's ok, but all that stuff will be generated by Easy Peasy at runtime. I really love Easy State simplicity.

**Comment by rainmanhhh** [comment]
just create a typescript version [react-osh](https://github.com/rainmanhhh/react-osh) and add computed value support(with smart cache)

**Comment by nitelite** [comment]
I love to see the new commits in this lib. It has quickly become my favorite way to manage state. I have been looking into how everything works to see if I could create a simpler version of this without a lot of the legacy stuff that monkey patches the scheduler etc, but I am sure there are reasons for it still being there.

react-osh looks good. Does it suffer from the same bug as react-easy-state when updating the value of an input field with a controlled value? r-e-s seems to make the cursor jump to the end of the text, if you try to set the cursor in the middle of the text field and start typing.

**Comment by nitelite** [comment]
> just create a typescript version [react-osh](https://github.com/rainmanhhh/react-osh) and add computed value support(with smart cache)

I have now switched from react-easy-state to react-osh for two of my projects, and the switch was very pain-free. API is the same, and it even fixed one of the bugs I had with updating text fields.

**Comment by solkimicreb** [comment]
The next release is coming early next week! It will include an exciting announcement too 🙂

**Comment by solkimicreb** [comment]
The package is moved to [@risingstack/react-easy-state](https://www.npmjs.com/package/@risingstack/react-easy-state) with no breaking changes. The new version (v6.2.0) is released under the new package with critical bug fixes and new features. Please migrate to the new package to get them (again: no breaking changes).

This also means that the project is moved under the company I work for (RisingStack) with an enthusiastic support team 🙂
