### ISSUE TITLE
React hooks

### ISSUE THREAD

**Issue by lishine** [RisingStack/react-easy-state#96]
Thinking to reimplement the view () so that to write useStore() instead of wrapping

**Comment by chemdemo** [comment]
See this repository：https://github.com/react-kit/hodux

**Comment by solkimicreb** [comment]
It is not possible to reduce the API and omit `view` without having hodux like selectors and we prefer to keep the current API. We will ship changes to play nicer with the hooks API in the next release though.

**Comment by solkimicreb** [comment]
The package is moved to [@risingstack/react-easy-state](https://www.npmjs.com/package/@risingstack/react-easy-state) from v6.2.0. Please move to that package for the new [`useEffect` alternative](https://github.com/RisingStack/react-easy-state#adding-side-effects).
